version: "3.4"

networks:
  new:

services:
  redis-cache:
    networks:
      new:
        aliases:
          - redis-cache
    image: redis:latest
    ports:
      - "6379:6379"
  postgres-db:
    image: postgres:latest
    networks:
      new:
        aliases:
          - database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 10s
      start_period: 20s
      retries: 5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123qwe123
      POSTGRES_DB: hezzl_test
  app:
    networks:
      - new
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      APP_ENV: docker
      APP_PORT: :8080

      DB_HOST: database
      DB_USER: postgres
      DB_PASS: 123qwe123
      DB_NAME: sovcom_people
      DB_SSLMODE: disable

      REDIS_DB: 0
      REDIS_HOST: redis-cache:6379
    depends_on:
      - redis-cache
      - postgres-db